version: "3.8"

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.2
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__WEBSERVER__RBAC: "True"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.session,airflow.api.auth.backend.basic_auth"
    _AIRFLOW_WWW_USER_USERNAME: admin
    _AIRFLOW_WWW_USER_PASSWORD: admin
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    AIRFLOW__WEBSERVER__SECRET_KEY: "_QPeeomhD1Rd5ZqUDt5smMSNqfDdg_73aYy5OEYE1dwpMI2tyodgbzplqKjK-RCzb_HrhDwAW53bdWVD7pG1ng"
    POSTGRES_CONN_URI: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-postgres==5.10.1 matplotlib==3.8.4"

  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./sql:/opt/airflow/sql
    - ./output:/opt/airflow/output
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: >
      -c "pip install -r /opt/airflow/requirements.txt && airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true"
    volumes:
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./sql:/opt/airflow/sql
      - ./output:/opt/airflow/output

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports: ["8080:8080"]

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

volumes:
  pgdata:
